In [1]:
import numpy as np

In [2]:
w = 3
w_inv = 5

In [3]:
def print_latex(m):
    for row in m:
        print(' & '.join([str(i) for i in row]) + ' \\\\ ')

In [4]:
m = np.empty((6, 6), dtype=int)

for i in range(6):
    for j in range(6):
        m[i][j] = w ** (i*j) % 7
        
print(m)

[[1 1 1 1 1 1]
 [1 3 2 6 4 5]
 [1 2 4 1 2 4]
 [1 6 1 6 1 6]
 [1 4 2 1 4 2]
 [1 5 4 6 2 3]]


In [5]:
m_inv = np.empty((6, 6), dtype=int)

for i in range(6):
    for j in range(6):
        m_inv[i][j] = w_inv ** (i*j) % 7
        
m_inv = (m_inv * 6) % 7

print(m_inv)

[[6 6 6 6 6 6]
 [6 2 3 1 5 4]
 [6 3 5 6 3 5]
 [6 1 6 1 6 1]
 [6 5 3 6 5 3]
 [6 4 5 1 3 2]]


In [6]:
p1 = np.array([1, 1, 1, 0, 0, 0])
p2 = np.array([-1, 2, 0, 1, 0, 0])

print(p1)
print(p2)

[1 1 1 0 0 0]
[-1  2  0  1  0  0]


In [7]:
p1_t = m @ p1 % 7
p2_t = m @ p2 % 7

print(p1_t)
print(p2_t)

[3 6 0 1 0 3]
[2 4 4 3 1 1]


In [8]:
p12_t = p1_t * p2_t % 7

print(p12_t)

[6 3 0 3 0 3]


In [9]:
p12 = m_inv @ p12_t % 7

print(p12)

[6 1 1 3 1 1]
